export const actionsEnums = {
  USERPROFILE_UPDATE_EDITING_LOGIN:  "USERPROFILE_UPDATE_EDITING_LOGIN",
  USERPROFILE_PERFORM_LOGIN: "USERPROFILE_PERFORM_LOGIN",
  STUDENTS_GET_LIST_REQUEST_COMPLETED: "STUDENTS_GET_LIST_REQUEST_COMPLETED"
};
