export const actionsEnums = {
  UPDATE_USERPROFILE_NAME : 'UPDATE_USERPROFILE_NAME ',
  UPDATE_USERPROFILE_FAVOURITE_COLOR: 'UPDATE_USERPROFILE_FAVOURITE_COLOR',
  MEMBER_REQUEST: 'MEMBER_REQUEST',
  MEMBER_REQUEST_COMPLETED: 'MEMBER_REQUEST_COMPLETED'  
}
