export const actionsEnums = {
  UPDATE_USERPROFILE_NAME: "UPDATE_USERPROFILE_NAME",
  UPDATE_USERPROFILE_FAVOURITE_COLOR: "UPDATE_USERPROFILE_FAVOURITE_COLOR",
  MEMBER_REQUEST_STARTED: "MEMBER_REQUEST_STARTED",
  MEMBER_REQUEST_COMPLETED: "MEMBER_REQUEST_COMPLETED",
  MEMBER_REQUEST_CANCELLED: "MEMBER_REQUEST_CANCELLED",
};
