export const actionsEnums = {
  USERPROFILE_UPDATE_EDITING_LOGIN:  "USERPROFILE_UPDATE_EDITING_LOGIN",
  USERPROFILE_PERFORM_LOGIN: "USERPROFILE_PERFORM_LOGIN",
  STUDENTS_GET_LIST_REQUEST_COMPLETED: "STUDENTS_GET_LIST_REQUEST_COMPLETED",
  STUDENT_GET_STUDENT_REQUEST_COMPLETED: "STUDENT_GET_STUDENT_REQUEST_COMPLETED",
  STUDENT_FIELD_VALUE_CHANGED_COMPLETED: "STUDENT_FIELD_VALUE_CHANGED_COMPLETED",
  STUDENT_SAVE_COMPLETED: "STUDENT_SAVE_COMPLETED",
  RESET_EDITING_STUDENT: "RESET_EDITING_STUDENT",
  FETCH_COUNTRY_LIST_REQUEST_COMPLETED: "FETCH_COUNTRY_LIST_REQUEST_COMPLETED",
  ADD_COUNTRY: "ADD_COUNTRY",
};
